### ISSUE TITLE
Can't run inside jest test

### ISSUE THREAD

**Issue by BackdoorTech** [Feirell/performance-test-runner#1] opened 2022-11-23 16:15 UTC
**Am having problem  running inside my test** 
my speed.test.ts file:

```javascript
import { PluginManager } from "live-plugin-manager";
import { PerformanceTestRunner } from "performance-test-runner";
import { runAndReport } from "performance-test-runner/lib/suite-console-printer";
import { performance } from "perf_hooks";
const manager = new PluginManager();

describe("PerFormance", () => {

  it('Teste dependecies', async () => {

    await manager.install("beast-orm","1.1.1");

    expect('time not exceeded').toBe('time not exceeded');
    
  }, 60000)


  it('Filter', async () => {

    const ptr = new PerformanceTestRunner();
    const {measure, speed} = ptr;

    measure('timestamp', () => {
      speed('performance.now', {performance}, () => {
        global.performance.now();
      });
  
      speed('Date.now', () => {
        Date.now();
      });
    });
  
    runAndReport(ptr);

    expect('time not exceeded').toBe('time not exceeded');
    
  }, 9000)

})

```

i get this

![Example Image](https://drive.google.com/uc?id=14e2tmfE_q4sjiRU9Y5feVNMyGJjf69mG)

You can replicate this error yourself
1. clone
**git clone https://github.com/BackdoorTech/Beast-ORM.git**
2. Install
**npm i**
3. change branch
**git checkout feature/speed-bug**
4. run test 
**npm run speed-test**

**Comment by Feirell** [comment] 2022-11-23 18:00
Greetings,

pretty cool to get the first issue to one of my projects :)

A couple of things about your case.
This package is meant to be used to construct https://www.npmjs.com/package/benchmark tests in a similar fashion as you can do with other unit testing frameworks like you do with jest etc.

**But** it is not supposed to work with them in tandem!
It does not require the runner, nor seems it to be working with it rather well.

If you add  `await` in the `runAndReport` line you remove the error, not quite sure why but it might be related to the way jest construct its contexts.

In any case you should not use this library in this way.
I would recommend you to write another file entirely (maybe `tests/performance/query.test.ts`) and then call it by `ts-node tests/performance/query.test.ts`.

Which might look something like that:

```typescript
import {PerformanceTestRunner} from "performance-test-runner";
import {runAndReport} from "performance-test-runner/lib/suite-console-printer";

// just an example you can import anything you would like here
import {queryFieldDirectly, queryFieldIndirectly} from "beast-orm";

const ptr = new PerformanceTestRunner();
const {measure, speed} = ptr;

measure('query alternatives', () => {
  speed('directly', {queryFieldDirectly}, () => {
    queryFieldDirectly();
  });

  speed('indirectly', {queryFieldIndirectly}, () => {
    queryFieldIndirectly();
  });
});

runAndReport(ptr);
```

Have a look at the README for remarks about code splitting etc.
And keep in mind that your operation should be non global, so it can be executed repeatedly.
Otherwise your test will have no real meaning after all because in context of the full call your implementation will only occupy a minority of the call time.
So for example if you would like to test how fast you package can read and write, you could construct a test but its result would be without real meaning when having an external dependency. 

Those test are only useful when directly comparing actions to alternatives.
So you might go ahead and import other libraries which are providing the same functionality and call them in another test cases of the same group to get some sort of relative meaning.

You could also compare them to generic actions (e.g. an array concat etc. so you can get a feeling for it) or your own alternatives if you, for example, want to create regression tests and want to see if you newer alternatives are actually faster.

**Comment by Feirell** [comment] 2022-12-05 09:40
I assume that you have made a decision, if you want to use this package in this way. I will close the issues, if you need further assistance feel free to reopen this issue or open a new one.

**Closed as completed by Feirell** 2022-12-05 09:40 UTC
